"""
Django settings for authdemo project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2^w%5mijr3h=p635#av(5&w7%3w-^ku7ywl(vx-ar5s-s9e4s1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
     #local apps
    'home.apps.HomeConfig',  #new
    'accounts.apps.AccountsConfig',  #new
   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'accounts.Member'   #new

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'authdemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  #new
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'authdemo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


##############################################################

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        #'ENGINE':'django.db.backends.postgresql',  #new (For use with postgresql)
        #'NAME':'authdemo',  #new
        #'USER':'postgres',   #new
        #'PASSWORD':'xyz12345', #new
        #'PORT':'',
  #new
    }
}

##############################################################










# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #new

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  #new


LOGIN_URL = '/login/'   #new
LOGIN_REDIRECT_URL = '/'  #new
LOGOUT_REDIRECT_URL = '/'  #new

MEDIA_URL = '/media/'     #new
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   #new

# We are dealing with the case of users registering with their
# own usernames, passwords etc.
# Many modern websites allow user authentication via a 
# social media account. That will be the topic of a future
# example. However if you need to get started on that now
# see:
# https://python-social-auth-docs.readthedocs.io/en/latest/index.html

########## GLOBAL SETTINGS ##################################

# You can find global settings in the virtual environment
#  Navigate to:
# Virtual Env/Lib/site-packages/django/conf

##############################################################

######## AUTHENTICATION WITH SOCIAL MEDIA ####################

# Registration using a social media accounts will be the topic
# of another set of videos. However if you need to do that right
# away here is a link to a library that will get you started:
# https://python-social-auth-docs.readthedocs.io/en/latest/index.html

#############################################################
